# BigEarthNet-MM | FedAvg | S1+S2 | local_epochs=50 (200 total effective epochs)
dataset: bge
training: fedavg
data_root: data/bge

model_name: bge_fedavg_s1_s2_le50
wandb_project: collab-mm-learning
use_wandb: false

modality: [s1, s2]
num_classes: 6
per_class_count: 100

backbone: cnn_backbone_resnet_groupbn
cnn_backbone_resnet_num_blocks: [2, 2, 2]
normalize_backbone: false
proj_type: cnn_proj_resnet
cnn_proj_resnet_num_blocks: [2]

loss_function: CrossEntropyLoss
optimizer_CLS: AdamW
lr_CLS: 0.001
weight_decay_CLS: 0.01
betas_CLS: [0.9, 0.999]
scheduler_CLS: step
step_size_CLS: 150
gamma_CLS: 0.1

global_rounds: 4
local_epochs: 50
batch_size: 32
num_workers: 4
pin_memory: true
prefetch_factor: 2

save_model: true
save_after_epoch: 150
recompute_batchnorm: true
seed: 42
